# run the tests on any PR targeting main
# we will want to update this to use docker-compose in the future, but for now, just make sure
# it builds

name: Go

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Build
      run: go build -v ./...
